version: '3'
services:
  jenkins:
    container_name: 'jenkins'
    image: 'jenkins:2.46.1-alpine'
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    links:
      - 'rabbitmq'
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.3.0'
    ports:
      - '9200:9200'
      - '9300:9300'
  logstash:
    container_name: 'logstash'
    build: 'logstash/'
    ports:
      - '9998:9998'
      - '9600:9600'
    links:
      - 'rabbitmq'
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.6.9-management-alpine'
    ports:
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  kibana:
    container_name: 'kibana'
    image: 'docker.elastic.co/kibana/kibana:5.3.0'
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    links:
      - 'elasticsearch'
