version: '3'
services:
  jenkins:
    container_name: 'jenkins'
    image: 'jenkins:2.46.1-alpine'
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    links:
      - 'rabbitmq'
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.3.0'
    ports:
      - '9200:9200'
      - '9300:9300'
  logstash:
    container_name: 'logstash'
    build: 'logstash/'
    ports:
      - '9998:9998'
      - '9600:9600'
    links:
      - 'rabbitmq'
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.6.9-management-alpine'
    ports:
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  kibana:
    container_name: 'kibana'
    image: 'docker.elastic.co/kibana/kibana:5.3.0'
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    links:
      - 'elasticsearch'
  # Monitoring
  cadvisor:
    image: google/cadvisor
    ports:
      - "8081:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  grafana:
    container_name: "grafana"
    image: grafana/grafana:4.2.0
    restart: always
    links:
      - influxdb:influxdb
    ports:
      - "3000:3000"
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root
  influxdb:
    container_name: "influxdb"
    image: influxdb:1.2.2-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
