version: '3'
services:
  jenkins:
    container_name: 'jenkins'
    image: 'jenkins:2.46.1-alpine'
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    links:
      - 'rabbitmq'
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.3.0'
    ports:
      - '9200:9200'
      - '9300:9300'
  logstash:
    container_name: 'logstash'
    build: 'logstash/'
    ports:
      - '9998:9998'
      - '9600:9600'
    links:
      - 'rabbitmq'
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.6.9-management-alpine'
    ports:
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  kibana:
    container_name: 'kibana'
    image: 'docker.elastic.co/kibana/kibana:5.3.0'
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    links:
      - 'elasticsearch'

  # Monitoring
  cadvisor:
    container_name: "cadvisor"
    image: google/cadvisor
    ports:
      - "8081:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  grafana:
    container_name: "grafana"
    image: grafana/grafana:4.2.0
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin
    links:
      - "prometheus"
  prometheus:
    container_name: "prometheus"
    build: "prometheus/"
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    links:
      - "cadvisor"
      - "node-exporter"
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sysfs'
      - '-collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    expose:
      - 9100
    ports:
      - "9100:9100"

